//vspeed = random_range(-0.1,-1)
image_speed = random_range(0.5,1)
image_index = random_range(0,4)
hsp = random_range(-2,2)
vsp = random_range(-1.3,1.3)
image_xscale = choose(1,-1)
image_yscale = choose(1,-1)
